version: '3.1'

services:

  wordpress:
    image: wordpress:5.3.2-php7.2-apache
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin1234
      WORDPRESS_DB_NAME: zenblocks
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: zenblocks
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: